# Generated by Django 4.2.4 on 2023-08-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=200)),
                ('origin_name', models.CharField(max_length=200)),
                ('image', models.URLField()),
            ],
        ),
    ]
